version: '3.8'
services:
  greenmail:
    image: greenmail/standalone:2.0.1
    restart: always
    container_name: up42-greenmail
    environment:
      # Enable GreenMail verbose mode
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose
    ports:
      - "3025:3025"
      - "3143:3143"
      - "3993:3993"
      - "3110:3110"
      - "8080:8080"
